<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK2NHHiK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK2NHHiK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK2NHHiK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK2NHHiK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK2NHHiK\App_KernelDevDebugContainer([
    'container.build_hash' => 'K2NHHiK',
    'container.build_id' => 'fba8e632',
    'container.build_time' => 1715558662,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK2NHHiK');
